name: exemples
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.4.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
   - assets/zawarudo.png

  fonts:
    - family: Yanone Kaffeesatz
      fonts:
        - asset: assets/YanoneKaffeesatz-Regular.ttf
        - asset: assets/YanoneKaffeesatz-ExtraLight.ttf
        - asset: assets/YanoneKaffeesatz-Light.ttf
        - asset: assets/YanoneKaffeesatz-Bold.ttf